train_datasets:
  - "tmp/behavior_local_rbm/behavior_local"

train_subsets:
  - [""]

eval_datasets:
  - "tmp/behavior_local_rbm/behavior_local"

eval_subsets:
  - [""]

max_frames_for_preprocessing: 32
video_frame_sampling: "uniform"
num_proc: 1
num_threads: 8
force_reprocess: false
cache_dir: "C:\\Users\\27642\\Desktop\\behavior\\robometer_processed_behavior"

precompute_embeddings: false
embeddings_cache_dir: "embeddings"
dinov2_model: "facebook/dinov2-base"
sentence_model: "sentence-transformers/all-MiniLM-L12-v2"
embedding_batch_size: 64
